{{- if not .Values.auth.existingSecret }}
{{- $name := include "quench-common.fullname" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- $pw := .Values.auth.password -}}
{{- if and (not $pw) $existing -}}
{{- $pw = index $existing.data "adminPassword" | b64dec -}}
{{- end -}}
{{- if not $pw -}}
{{- $pw = randAlphaNum 24 -}}
{{- end -}}
{{- $cookie := .Values.auth.erlangCookie -}}
{{- if and (not $cookie) $existing -}}
{{- $cookie = index $existing.data "erlangCookie" | b64dec -}}
{{- end -}}
{{- if not $cookie -}}
{{- $cookie = randAlphaNum 32 -}}
{{- end -}}
{{- $authSecret := .Values.auth.secret -}}
{{- if and (not $authSecret) $existing -}}
{{- $authSecret = index $existing.data "cookieAuthSecret" | b64dec -}}
{{- end -}}
{{- if not $authSecret -}}
{{- $authSecret = randAlphaNum 32 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
type: Opaque
data:
  adminPassword: {{ $pw | b64enc | quote }}
  erlangCookie: {{ $cookie | b64enc | quote }}
  cookieAuthSecret: {{ $authSecret | b64enc | quote }}
{{- end }}
