{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
{{- $name := include "quench-common.fullname" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- $ak := .Values.auth.accessKey -}}
{{- if and (not $ak) $existing -}}
{{- $ak = index $existing.data "access-key" | b64dec -}}
{{- end -}}
{{- if not $ak -}}
{{- $ak = randAlphaNum 20 -}}
{{- end -}}
{{- $sk := .Values.auth.secretKey -}}
{{- if and (not $sk) $existing -}}
{{- $sk = index $existing.data "secret-key" | b64dec -}}
{{- end -}}
{{- if not $sk -}}
{{- $sk = randAlphaNum 40 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ $ak | b64enc | quote }}
  secret-key: {{ $sk | b64enc | quote }}
{{- end }}
