apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quench-common.fullname" . }}-web
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "zabbix.componentLabels" (dict "ctx" . "component" "web") | nindent 6 }}
  template:
    metadata:
      {{- include "quench-common.podAnnotations" . | nindent 6 }}
      labels:
        {{- include "zabbix.componentLabels" (dict "ctx" . "component" "web") | nindent 8 }}
        {{- include "quench-common.podLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "zabbix.serviceAccountName" . }}
      securityContext:
        {{- include "quench-common.podSecurityContext" . | nindent 8 }}
      {{- include "quench-common.podSpecFields" . | nindent 6 }}
      containers:
        - name: web
          image: {{ include "zabbix.webImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- include "quench-common.containerSecurityContext" . | nindent 12 }}
          env:
            {{- include "zabbix.dbEnv" . | nindent 12 }}
            - { name: ZBX_SERVER_NAME, value: {{ .Values.web.serverName | quote }} }
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket: { port: http }
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /index.php, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quench-common.fullname" . }}-web
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "zabbix.componentLabels" (dict "ctx" . "component" "web") | nindent 4 }}
