apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quench-common.fullname" . }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "quench-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quench-common.selectorLabels" . | nindent 8 }}
        {{- include "quench-common.podLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "quench-common.fullname" . }}
      automountServiceAccountToken: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 60
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: tigera-operator
          image: {{ include "quench-common.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-manage-crds=true"]
          env:
            - {name: WATCH_NAMESPACE, value: ""}
            - name: POD_NAME
              valueFrom: {fieldRef: {fieldPath: metadata.name}}
            - {name: OPERATOR_NAME, value: {{ include "quench-common.fullname" . | quote }}}
            - {name: OPERATOR_NAMESPACE, value: {{ .Release.Namespace | quote }}}
            - {name: TIGERA_OPERATOR_INIT_IMAGE_VERSION, value: "v{{ .Values.operatorVersion }}"}
          envFrom:
            # API server address for clusters where the kube-proxy service IP is not routable yet
            - configMapRef: {name: kubernetes-services-endpoint, optional: true}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities: {drop: [ALL]}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - {name: var-lib-calico, mountPath: /var/lib/calico, readOnly: true}
      volumes:
        - name: var-lib-calico
          hostPath: {path: /var/lib/calico}
