{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "quench-common.fullname" . }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "quench-common.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: dns-udp
          protocol: UDP
        - port: dns-tcp
          protocol: TCP
    {{- if .Values.api.enabled }}
    - ports:
        - port: api
          protocol: TCP
      from:
        - podSelector: {}
        {{- range .Values.networkPolicy.apiAllowNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
