apiVersion: v1
kind: Service
metadata:
  name: {{ include "quench-common.fullname" . }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
    {{- if .Values.readServer.enabled }}
    - name: read
      port: {{ .Values.service.readPort }}
      targetPort: read
    {{- end }}
  selector:
    {{- include "quench-common.selectorLabels" . | nindent 4 }}
