{{- if and (include "kong.dbMode" .) (not .Values.postgres.existingSecret) .Values.postgres.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kong.secretName" . }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}
{{- end }}
