apiVersion: v1
kind: Service
metadata:
  name: {{ include "quench-common.fullname" . }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      name: grpc
      protocol: TCP
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      name: http
      protocol: TCP
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      name: metrics
      protocol: TCP
  selector:
    {{- include "quench-common.selectorLabels" . | nindent 4 }}
