{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quench-common.fullname" . }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
type: Opaque
data:
  token-hmac-secret-key: {{ include "centrifugo.resolveSecret" (dict "ctx" . "key" "token-hmac-secret-key" "explicit" .Values.secrets.tokenHmacSecretKey) | b64enc | quote }}
  http-api-key: {{ include "centrifugo.resolveSecret" (dict "ctx" . "key" "http-api-key" "explicit" .Values.secrets.apiKey) | b64enc | quote }}
  admin-password: {{ include "centrifugo.resolveSecret" (dict "ctx" . "key" "admin-password" "explicit" .Values.secrets.adminPassword) | b64enc | quote }}
  admin-secret: {{ include "centrifugo.resolveSecret" (dict "ctx" . "key" "admin-secret" "explicit" .Values.secrets.adminSecret) | b64enc | quote }}
{{- end }}
