apiVersion: v1
kind: Service
metadata:
  name: {{ include "quench-common.fullname" . }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: valkey
      name: valkey
  selector:
    {{- include "quench-common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: primary
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "valkey.primary.fullname" .) }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.port }}
      targetPort: valkey
      name: valkey
  selector:
    {{- include "quench-common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: primary
