apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quench-common.fullname" . }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
data:
  clamd.conf: |-
    {{- include "clamav.clamdConf" . | nindent 4 }}
  freshclam.conf: |-
    {{- include "clamav.freshclamConf" . | nindent 4 }}
{{- if .Values.customSignatures }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quench-common.fullname" . }}-signatures
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
data:
  {{- range $file, $content := .Values.customSignatures }}
  {{ $file }}: |-
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
