apiVersion: v2
name: zookeeper
description: Quenchworks hardened Apache ZooKeeper. Minimal, nonroot, 0-CVE image pinned by digest.
type: application
version: 0.0.2
appVersion: "3.9.5"
icon: https://raw.githubusercontent.com/quenchworks/.github/main/profile/assets/chart-icon.png
home: https://quenchworks.mkabumattar.com
keywords:
  - zookeeper
  - coordination
  - streaming
  - messaging
  - consensus
maintainers:
  - name: QuenchWorks
    email: quenchworks@mkabumattar.com
    url: https://github.com/quenchworks
sources:
  - https://github.com/quenchworks/charts
  - https://github.com/apache/zookeeper
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: source
      url: https://github.com/quenchworks/charts
    - name: image
      url: https://github.com/quenchworks/images
  artifacthub.io/signKey: |
    fingerprint: keyless (cosign / Sigstore)
    url: https://github.com/quenchworks/.github/blob/main/SECURITY.md
  artifacthub.io/category: streaming-messaging
  artifacthub.io/images: |
    - name: zookeeper
      image: ghcr.io/quenchworks/images/zookeeper@sha256:d135227512c944e3c829cf05de33f332391076611f9f3f90f517cd268b032e40
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
dependencies:
  - name: quench-common
    version: 0.0.1
    repository: oci://ghcr.io/quenchworks/charts
