apiVersion: v2
name: zookeeper
description: Quenchworks hardened Apache ZooKeeper. Minimal, nonroot, 0-CVE image pinned by digest.
type: application
version: 0.0.4
appVersion: "3.9.5"
icon: https://raw.githubusercontent.com/quenchworks/.github/main/profile/assets/chart-icon.png
home: https://quench-works.com
keywords:
  - zookeeper
  - coordination
  - streaming
  - messaging
  - consensus
maintainers:
  - name: QuenchWorks
    email: info@quench-works.com
    url: https://github.com/quenchworks
sources:
  - https://github.com/quenchworks/charts
  - https://github.com/apache/zookeeper
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: source
      url: https://github.com/quenchworks/charts
    - name: image
      url: https://github.com/quenchworks/images
  artifacthub.io/signKey: |
    fingerprint: keyless (cosign / Sigstore)
    url: https://github.com/quenchworks/.github/blob/main/SECURITY.md
  artifacthub.io/category: streaming-messaging
  artifacthub.io/images: |
    - name: zookeeper
      image: ghcr.io/quenchworks/images/zookeeper@sha256:9cc78adc918d7cb3f8a4a8da75df88d98eed33df2ea3922f5ebce5699e4750a1
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
dependencies:
  - name: quench-common
    version: 0.0.1
    repository: oci://ghcr.io/quenchworks/charts
