{{- if and .Values.media.persistence.enabled (not .Values.media.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "quench-common.fullname" . }}-media
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
  {{- with .Values.media.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes: {{ .Values.media.persistence.accessModes }}
  {{- with .Values.media.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.media.persistence.size }}
{{- end }}
