#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# ///
"""Vendor the linkerd-ONLY CRDs into quench/linkerd-crds/templates/crds.yaml.

    uv run scripts/gen-linkerd-crds.py <edge-version> [--check]

Upstream's charts/linkerd-crds also ships the Gateway API route CRDs, and they
are 696KB of its 707KB. We do NOT take those: quench/gateway-api-crds already
owns those names, two owners of one cluster-scoped CRD means whichever applies
last wins, and 707KB crowds Helm's 1,048,576-byte release Secret ceiling that
the envoy-gateway chart walked into once.

Upstream's files are Helm templates carrying four expressions, all in metadata,
one of which is `include "partials.annotations.created-by"` from upstream's own
library chart. The CRD SPEC is vendored byte for byte, because that is the API
contract; the metadata block is replaced with this chart's own labels so no
upstream library is needed.

--check regenerates into memory and exits non-zero if the shipped file differs,
which is what the release workflow runs so a hand-edit cannot ship.
"""
import re
import subprocess
import sys
import pathlib

BASE = "https://raw.githubusercontent.com/linkerd/linkerd2/edge-{ver}/charts/linkerd-crds/templates"

# Order is deliberate: the two the destination controller needs at startup
# first, then the rest of the policy set, then workload.
FILES = [
    "serviceprofile.yaml",
    "policy/server.yaml",
    "policy/server-authorization.yaml",
    "policy/authorization-policy.yaml",
    "policy/meshtls-authentication.yaml",
    "policy/network-authentication.yaml",
    "policy/egress-network.yaml",
    "policy/http-local-ratelimit-policy.yaml",
    "workload/external-workload.yaml",
]

EXPECTED_NAMES = {
    "serviceprofiles.linkerd.io",
    "servers.policy.linkerd.io",
    "serverauthorizations.policy.linkerd.io",
    "authorizationpolicies.policy.linkerd.io",
    "meshtlsauthentications.policy.linkerd.io",
    "networkauthentications.policy.linkerd.io",
    "egressnetworks.policy.linkerd.io",
    "httplocalratelimitpolicies.policy.linkerd.io",
    "externalworkloads.workload.linkerd.io",
}

# Upstream's metadata block, replaced wholesale. Matching on the `include` line
# is what makes this safe: if upstream restructures the block the pattern stops
# matching and the assertions below fail loudly rather than emitting a template
# that still references a library chart we do not ship.
UPSTREAM_META = re.compile(
    r"  annotations:\n"
    r'    \{\{ include "partials\.annotations\.created-by" \. \}\}\n'
    r"  labels:\n"
    r'    helm\.sh/chart: \{\{ \.Chart\.Name \}\}-\{\{ \.Chart\.Version \| replace "\+" "_" \}\}\n'
    r"    linkerd\.io/control-plane-ns: \{\{\.Release\.Namespace\}\}\n"
)

OURS = """  annotations:
    {{- if .Values.crds.keep }}
    helm.sh/resource-policy: keep
    {{- end }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    linkerd.io/control-plane-ns: {{ .Release.Namespace }}
"""

HEADER = """{{- /* GENERATED by scripts/gen-linkerd-crds.py, do not hand-edit.

     The linkerd-ONLY CustomResourceDefinitions from linkerd/linkerd2
     charts/linkerd-crds, at the appVersion this chart declares. Each CRD spec
     is upstream's, byte for byte; only the metadata annotations and labels are
     this chart's, so no upstream library chart is required.

     Upstream's bundle also carries the Gateway API route CRDs. Those are NOT
     here on purpose: quench/gateway-api-crds owns those names, and a
     cluster-scoped CRD with two owners belongs to whichever applied last.

     Re-run the generator to update; the release workflow runs it with --check
     and refuses to publish when this file and upstream disagree. */}}
"""


def fetch(ver: str) -> str:
    out = [HEADER]
    seen = set()
    for f in FILES:
        url = f"{BASE.format(ver=ver)}/{f}"
        r = subprocess.run(["curl", "-fsSL", url], capture_output=True, text=True)
        if r.returncode != 0 or not r.stdout.strip():
            sys.exit(f"!! could not fetch {url}")
        body = r.stdout
        if not UPSTREAM_META.search(body):
            sys.exit(f"!! {f}: upstream metadata block did not match; the shape changed, "
                     f"re-read it before regenerating")
        body = UPSTREAM_META.sub(OURS, body)
        name = re.search(r"^  name: (\S+)$", body, re.M)
        if not name:
            sys.exit(f"!! {f}: no CRD name found")
        seen.add(name.group(1))
        if "{{ include" in body or "partials." in body:
            sys.exit(f"!! {f}: an upstream library reference survived the rewrite")
        out.append(body if body.startswith("---") else "---\n" + body)
    missing = EXPECTED_NAMES - seen
    extra = seen - EXPECTED_NAMES
    if missing or extra:
        sys.exit(f"!! CRD set changed. missing={sorted(missing)} unexpected={sorted(extra)}")
    return "".join(out)


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        print(__doc__)
        return 2
    ver = args[0]
    target = pathlib.Path(__file__).resolve().parent.parent / "quench/linkerd-crds/templates/crds.yaml"
    generated = fetch(ver)
    if "--check" in sys.argv:
        if not target.exists():
            print(f"!! {target} does not exist")
            return 1
        if target.read_text() != generated:
            print(f"!! {target} differs from upstream edge-{ver}; re-run the generator")
            return 1
        print(f"ok crds.yaml matches linkerd2 edge-{ver} ({len(EXPECTED_NAMES)} CRDs)")
        return 0
    target.write_text(generated)
    print(f"wrote {target} from linkerd2 edge-{ver}: {len(EXPECTED_NAMES)} CRDs, {len(generated)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
