apiVersion: v2
name: rabbitmq
description: Quenchworks hardened RabbitMQ. Minimal, nonroot, 0-CVE image pinned by digest.
type: application
version: 0.0.1
appVersion: "4.3.1"
icon: https://raw.githubusercontent.com/quenchworks/.github/main/profile/assets/chart-icon.png
home: https://quenchworks.mkabumattar.com
sources:
  - https://github.com/rabbitmq/rabbitmq-server
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: source
      url: https://github.com/quenchworks/charts
    - name: image
      url: https://github.com/quenchworks/images
  artifacthub.io/signKey: |
    fingerprint: keyless (cosign / Sigstore)
    url: https://github.com/quenchworks/.github/blob/main/SECURITY.md
dependencies:
  - name: quench-common
    version: 0.0.0
    repository: oci://ghcr.io/quenchworks/charts
