apiVersion: v2
name: rabbitmq
description: Quenchworks hardened RabbitMQ. Minimal, nonroot, 0-CVE image pinned by digest.
type: application
version: 0.0.3
appVersion: "4.3.1"
icon: https://raw.githubusercontent.com/quenchworks/.github/main/profile/assets/chart-icon.png
home: https://quenchworks.mkabumattar.com
keywords:
  - rabbitmq
  - messaging
  - streaming
  - amqp
  - queue
maintainers:
  - name: QuenchWorks
    email: quenchworks@mkabumattar.com
    url: https://github.com/quenchworks
sources:
  - https://github.com/quenchworks/charts
  - https://github.com/rabbitmq/rabbitmq-server
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: source
      url: https://github.com/quenchworks/charts
    - name: image
      url: https://github.com/quenchworks/images
  artifacthub.io/signKey: |
    fingerprint: keyless (cosign / Sigstore)
    url: https://github.com/quenchworks/.github/blob/main/SECURITY.md
  artifacthub.io/category: streaming-messaging
  artifacthub.io/images: |
    - name: rabbitmq
      image: ghcr.io/quenchworks/images/rabbitmq@sha256:17ea372ffe35d58132b1b40fe4093729a0656650c60732088e8c2efe91367f5b
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
dependencies:
  - name: quench-common
    version: 0.0.1
    repository: oci://ghcr.io/quenchworks/charts
