{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quench-common.fullname" . }}-script
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
data:
  {{ .Values.scriptFileName }}: |
    {{- .Values.script | nindent 4 }}
{{- end }}
