{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envoy.configMapName" . }}
  labels:
    {{- include "quench-common.labels" . | nindent 4 }}
data:
  # Mounted at /etc/envoy/envoy.yaml and passed to `envoy` via -c.
  envoy.yaml: |-
    {{- include "envoy.config" . | nindent 4 }}
{{- end }}
